package com.realdolmen.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Entity to be used in the ORM to store data about an occupation. An occupation can be anything the user can do for a
 * limited period. Occupations can be divided into two classes: {@link Project}s and {@link GenericOccupation}s.
 */
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public abstract class Occupation {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    @NotNull(message = "name")
    private String name;

    private String description;

    public Occupation() {
    }

    /**
     * ID generated by JPA using an automatic generation strategy.
     *
     * @return the generated ID
     */
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
